### ISSUE TITLE
Pipeline

### ISSUE THREAD

**Issue by ShalokShalom** [dbrattli/FSlash#1]
I understand your decision, to not use operator overloading.
To frame my following opposition to it, here my background:

I can not use FSharp in my current project, since it is barely implemented. 

Python is an alternative. Something like [Coconut](http://coconut-lang.org/) is awesome, but its editor support is limited and I like good syntax highlighting. 

After looking for a good hour through all kinds of Stackoverflow posts, PyPi, and several other sources to find at least a proper pipe, did I finally stumble over your project and was finally in *Aww O.O*

I finally found *it*, and then I read this:

![Screenshot_2020-10-11-11-14-58-81](https://user-images.githubusercontent.com/6344099/95674957-0a508500-0bb4-11eb-95ab-6e600f3bf79e.jpg)

Just to be honest: This is how F# code looks like:

![Screenshot_2020-10-11-11-36-31-62](https://user-images.githubusercontent.com/6344099/95675252-20f7db80-0bb6-11eb-93f0-93140ef4f008.jpg)

I dont see any sense in a FSharp library for Python, that does not allow me to do that.

I can not emphasis enough, how important the pipeline operator is for me, its just fundamental to how FSharp feels and works for me. :)

Especially to place them into a new line, which is how idiomatic FSharp looks and feels.

Its also easier, to apply tutorials.

I understand that |> is probably not possible without recompiling and that overloading an already used operator is confusing, while I strongly suggest to adopt one that is not in broader use, or give the option to use | or >> anyway

I really see the point of avoiding confusion, while I dont work in a team - like most coders, especially in the open-source field - and reading into code based is always a struggle and this makes code at least more unambiguous and it's important to me, to be able to use FSharps traditional method.

It confuses me much more, to do it the way you implemented it. 

Thanks a lot!

**Comment by dbrattli** [comment]
In F/ this would currently look like:

```py
def expect_string(expected_string):
    return pipe(
        expected_string,
        stringToCharList,
        List.map(expectChar),
        sequenceParsers,
        mapParser(charListAsString)
    )
```

So you are free to put each operator in the pipeline on separate lines.

**Comment by ShalokShalom** [comment]
Thanks a lot

**Comment by ShalokShalom** [comment]
You might like to showcase this in the documentation

**Comment by AXGKl** [comment]
@ShalokShalom I was using Dag's RxPython (v2) for a few years, before it had the version with the pipe function in it. My first reaction to their version 3 was the same as yours. I was so in love with the "dot chained" operator pipelines, that I hated the idea to have to write all in plain old python functions and put stupid boring commas between the operators. 
I'm not the brightest guy unfortunately, so I did not immediately see the obvious - found that only after I forced myself to work with it.
*It's a game changer!*, at least for what I wanted it for - and I'm so glad Dag took the work and made it happen in RxPY, when ReactiveX standardized .pipe(...) 

Because now I can get my processing chain specs from *anywhere*, e.g. from json over the network, created by other people.
All you have to do is replace function names from the spec by the functions themselves (in map, or other ops dependent what you want to offer in such specs and possibly turned into partials, when parametrized). And working with lists is nice in python.

Then you can throw the spec pretty much as is into the pipe operator `.pipe(*my_mapped_function_list)`  and you just built a working computing pipeline.

Yes, would have been possible with meta programming tricks also by dot chaining the functions - but latest when you want to go recursive or let the guys on the other side define if-else or async stuff or data merging operations it gets really nasty. I always ended up with trying to explain the domain expert guys, who defined what should happen when, that they should express their stuff within the (Reactive) framework. But normally they did not pick it up, they could not overcome the initial understanding barrier. Now with pipe I can abstract that away from what they care about, business flows.

Trying to say: With pipe, composability is just out of the box and just fits with what python as to offer: variable length functions, partials, kw args.

So, yeah, I love "pipe" meanwhile, love on second sight, but those usually last longer anyway ;-)

**Comment by ShalokShalom** [comment]
Wonderful, I didn't know about that 🤭

Do you consider this as something that is worth finding its way into the Readme?

I personally feel the comment above can be copied into it almost 1:1
Thanks 👍🏻

**Comment by ShalokShalom** [comment]
@AXGKl My 2 Cents: Reactive programming got popularised due to Elm. It was the first commercially used, production-ready implementation of a reactive pattern and brought a lot more to the table, that complemented it.

React then took one aspect, put it on top of .. Javascript and called it a day. Since people dont like studing new things, was the jump to React easier for them - even if it meant more pain in the long run.

In case you are interested into this kind of programming:
Elm gave FRP up, since it found something even more intriguing: The Elm Architecture. And that one is also, what gets now copied all over the place: FSharp with Elmish and WebSharper MVU and OCaml with Bucklescript TEA, Elm itself and lots of other implementations.

All they have proper type inferrence and a HM type system.
In case you are truly interested into FRP, you might want to look into other languages, and how they implement that concept.

**Comment by AXGKl** [comment]
@ShalokShalom, hey. Yes, I played around with elm back then, when I was doing a projects using Redux and the creator constantly mentioned elm as his inspiration. React was never an option for me and I have no idea even why they named this thing like they did. Svelte should be called React or nowadays Angular ;-)
And yes, would I do a frontend project again, I'd definetly go again for an immutable state model, where model changes trigger view updates, deterministic at any time, alone from the model,  like in elm (and as you say, which made it also into the F# web architecture). 
The only deviation: I would always feed the changes into an event stream[1] and not dispatch and reduce updates directly. And that concept of an (better: THE) event stream as first class design concern, I find still, after many years  absolutely the right way to think about the problems, at least in my domain, frontend anway but also backend. Far more important than abstraction or encapsulation concerns or data shape and all that stuff...  And yes, also more important than purity, i.e. concerning functional or not. Especially in python immutability anyway is *pretty* expensive, so yes, as you say: When I really want to do FRP I'd look for another language and after this here it would not be clojure anymore but F# - so excited you both seem to be about (thanks for the hints btw)

[1]: To be clear: With "Event Stream" I mean it in the sense of ReactiveX, not to be confused with FRP. You can pump mutable objects through a ReactiveX pipeline and its up to you if you mess up the state of those within the stream or if you do it functional. They don't impose anything on you and you'll find out the hard way that you better deepcopy here and there ;-)
But what they DO care about is: WHEN does stuff happen. **Time** - with it you get a tight grip on time: The expensive stuff only happens when someone is interested in its results and it happens at a pace you have 100% control over - at any *time*.

<party talk>
I'm actually a education wise a particle physicist, so the idea that the system behaves differently, dependent on observation was and still is totally resonating with me, plus: Hey, reality outside this IT world is 4 dimensional - but 3 of those dimensions are gone within the software we write, only one is left: *time* :-)    
</party talk>

As said, I'll see if it makes sense to combine this with F# (or FSlash to begin with, guess its the most convenient start into this world, for a python guy)

**Comment by ShalokShalom** [comment]
Oh, thats cool. I started from the beginning with functional programming and all this stuff, since I watched a lot of videos and read articles about this topic and the experts seemed all to recommend it, while the overall population seemed very fond of what they are used to, despite its flaws.

I found many useful concepts, currently is Godot a great thing: https://medium.com/swlh/what-makes-godot-engine-great-for-advance-gui-applications-b1cfb941df3b

Especially for you being interested into particle physics, could that be cool, we support also Python and F# as community tools and the upcoming version has a new particle system:
https://godotengine.org/article/improvements-gpuparticles-godot-40

**Comment by AXGKl** [comment]
Wow this godot looks massive. It's insane what the opensource world is able to achieve.... Many thanks for the pointer!

PS: I've put most of my stuff into details above, sorry for the post-editing. But this is the first issue of a Dag Brattli project - and your question was exactly the perfect one to get answered by Dag himself - don't want to distract people interested in FSlash. 

<details><summary>PS2: particles...</summary>
The particles I meant are on yet another scale - and *my* explaination of their "crazy" [behaviour](https://www.youtube.com/watch?v=SzAQ36b9dzs) is that that the universe seems to be programmed ReactiveX style. No traveling back in time like most Physicists think but subscription pipelines built before any ~~message~~ particle is emitted.
Even the terminology fits, observable streams everywhere :-)
</details>
